# Generated by Django 5.1.3 on 2024-11-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartproducts',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
